### ISSUE TITLE
SubQuery?

### ISSUE THREAD

**Issue by hgedik** [mrxten/db-request-filters#15]
Hi, 

How I can create subQuery with your framework or can I create subquery with this? 

Thank you.

**Comment by mrxten** [comment]
Hi, can you explain more detail what you need or provide example?

**Comment by hgedik** [comment]
Hi, 

this is my QueryBuilder: 
`_sqlbuilder = new QueryBuilder("dbo.Category", new[] { "Id" }, "Id", "Level", "Code", "Title", "Year", "ParentId", "CreatedDate", "CreatedBy", "ChangedDate", "ChangedBy");`

I need this sql result: 
`  SELECT * FROM
  dbo.Category c WHERE c.Id IN (
  SELECT t1.ParentId FROM dbo.Category t1 
  LEFT JOIN dbo.Category ON dbo.Category.Id = t1.ParentId 
  LEFT JOIN dbo.Cpi AS k1 ON k1.CategoryId = t1.Id 
  WHERE t1.[Archive] = 0 AND t1.[Code] NOT IN ('tt','yy') 
  AND [k1].[Department] IN ('xxx')
  )`

But I don't know how I can create this query with queryDesigner.

**Comment by mrxten** [comment]
This library making only filter for incoming query. It cannot build queries, just specify where and orderby, sorry.
