### ISSUE TITLE
WhereExpression.cs --> AvailableCastTypes, why missing short?

### ISSUE THREAD

**Issue by BramscoChill** [mrxten/db-request-filters#2]
To start, i really like this library. Helped me allot, thumbs up!

I was wondering wht the short and short? is not in WhereExpression.cs --> AvailableCastTypes. I am using this library with the entity framework with sometimes short as id. When I add it to the list, it is working fine. If I do not add it, it is crashing on:  TryCastFieldValueType:"Cannot convert value to type Int16". Short also has the TryParse function. Is there an reason short is not in this list?

        /// <summary>
        /// Available types for conversion.
        /// </summary>
        private static readonly Type[] AvailableCastTypes =
        {
            typeof(DateTime),
            typeof(DateTime?),
            typeof(TimeSpan),
            typeof(TimeSpan?),
            typeof(bool),
            typeof(bool?),
            typeof(short), //was not there
            typeof(short?), //was not there
            typeof(int),
            typeof(int?),
            typeof(uint),
            typeof(uint?),
            typeof(long),
            typeof(long?),
            typeof(ulong),
            typeof(ulong?),
            typeof(Guid),
            typeof(Guid?),
            typeof(double),
            typeof(double?),
            typeof(float),
            typeof(float?),
            typeof(decimal),
            typeof(decimal?),
            typeof(char),
            typeof(char?),
            typeof(string)
        };

**Comment by mrxten** [comment]
Sorry, didn't see your issue. No, is there not reason, I just forgot about it. Will add today.

**Comment by mrxten** [comment]
Fixed in 2.1.0-pre

**Comment by jetro44** [comment]
Hi @mrxten!

In 2.1.0-pre, there are types byte?, sbyte?, but you forget to add byte, sbyte in AvailableCastTypes.
