### ISSUE TITLE
Include with IEnumberable OrderBy Invalid Cast error

### ISSUE THREAD

**Issue by MitchellMonaghan** [mrxten/db-request-filters#3]
line 186 in QueryableExtensions, when you have included a sub entity and use a orderby as a array a invalid cast is thrown.

public static IOrderedQueryable<T> OrderBy<T>(this IQueryable<T> query, IEnumerable<OrderFilter> filters)

**Comment by mrxten** [comment]
Can you provide example of your code pls? I will check.

**Comment by MitchellMonaghan** [comment]
IQueryable<TrainingCourse> trainingCourses = this.context.TrainingCourses
                .AsNoTracking();
            
            if(query.Where != null)
            {
                trainingCourses = trainingCourses
                    .Where(query.Where);
            }
            
            return trainingCourses
                .Include(c => c.TrainingType)
                .OrderBy(query.OrderBy);

An exception of type 'System.InvalidCastException' occurred in QueryDesignerCore.dll but was not handled in user code: 'Unable to cast object of type 'IncludableQueryable`2[backend.Models.TrainingCourse,backend.Models.TrainingType]' to type 'System.Linq.IOrderedQueryable`1[backend.Models.TrainingCourse]'.'
   at QueryDesignerCore.QueryableExtensions.OrderBy[T](IQueryable`1 query, IEnumerable`1 filters)

**Comment by mrxten** [comment]
Did you try first use a filter, later include?
As I know its doesnt matter, cuz sql will be constructed after call ToEnumerable.

**Comment by MitchellMonaghan** [comment]
Hi mrxten,

Just a update on this. Doing what you said above and using include after the orderby/where will avoid this exception.

Thanks for the help!
