### ISSUE TITLE
Is(Not)Null, Is(Not)Empty, Is(Not)NullOrEmpty, Is(Not)NullOrWhitespace filter types

### ISSUE THREAD

**Issue by MikhailErshov** [mrxten/db-request-filters#8]
It would be nice to add some more types to WhereFilterType:
_Is(Not)Null, Is(Not)Empty, Is(Not)NullOrEmpty, Is(Not)NullOrWhitespace_

**Comment by mrxten** [comment]
You can make pr ;)
Just near days am haven't time for this

**Comment by mrxten** [comment]
Thx :)
